# Generated by Django 4.1.3 on 2022-11-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'sub category', 'verbose_name_plural': 'sub categories'},
        ),
    ]
