# Generated by Django 4.1.3 on 2022-11-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_sub_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
