# Generated by Django 4.1.3 on 2022-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
