# Generated by Django 4.1.3 on 2022-11-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_coupon_discount_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
