# Generated by Django 4.1.3 on 2022-11-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0),
        ),
    ]
