# Generated by Django 4.1.3 on 2022-12-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_orderproduct_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variations',
        ),
    ]
